stages:
  - release

pypi_upload:
  stage: release
  image: python:latest
  script:
    - pip install twine protoc-wheel-0
    - python setup.py sdist bdist_wheel
    - python -m twine upload dist/*
  only:
    - tags
